[book]
authors = ["mail@emuell.net"]
language = "en"
src = "src"
title = "pattrns"

[build]
build-dir = "out"
create-missing = false

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/renoise/pattrns"
edit-url-template = "https://github.com/emuell/pattrns/edit/master/docs/{path}"
additional-css = ["src/styles.css"]
sidebar-header-nav = false
