name: Benchmark

on:
  workflow_run:
    workflows: ["build"]
    types: [ completed ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          cache-key: "pattrns-build"

      - name: Benchmark
        uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.event.workflow_run.head_branch }}
