name: Benchmark

on:
  workflow_call:

concurrency:
  group: benchmarks-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  runBenchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          cache-key: "pattrns-build"

      - name: Benchmark
        uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
