name: Build & Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          components: clippy
          cache-key: "pattrns-build"

      - name: Build
        run: cargo build --verbose

      - name: Clippy
        run: cargo clippy --verbose -- -D warnings

      - name: Run tests
        run: cargo test --verbose

  benchmark:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v2
        with:
          cache-key: "pattrns-build"

      - name: Benchmark
        uses: boa-dev/criterion-compare-action@v3
        with:
          branchName: ${{ github.base_ref }}
